# Project -3 Application of Classification Models

In [ ]:
Dataset Link

https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data

Problem 1:
Prediction task is to determine whether a person makes over 50K a year.

Problem 2:
Which factors are important

Problem 3:
Which algorithms are best for this dataset

In [224]:
import pandas as pd
import numpy as np
urlTrain = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
urlTest = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test'

train_set = pd.read_csv(urlTrain, header = None)
test_set = pd.read_csv(urlTest, skiprows = 1, header = None)

col_labels = ['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status','occupation','relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week','native_country', 'wage_class']

train_set.columns = col_labels
test_set.columns = col_labels

In [225]:
train_set.head(5)

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country wage_class  
0          2174             0              40   United-States      <=50K  
1             0             0              13   United-States      <=50K  
2             0             0              40   United-States      <=50K  
3             0             0              40   United-States      <=50K  
4             0             0              40            Cuba      <=50K

In [226]:
test_set.head(5)

age   workclass  fnlwgt      education  education_num       marital_status  \
0   25     Private  226802           11th              7        Never-married   
1   38     Private   89814        HS-grad              9   Married-civ-spouse   
2   28   Local-gov  336951     Assoc-acdm             12   Married-civ-spouse   
3   44     Private  160323   Some-college             10   Married-civ-spouse   
4   18           ?  103497   Some-college             10        Never-married   

           occupation relationship    race      sex  capital_gain  \
0   Machine-op-inspct    Own-child   Black     Male             0   
1     Farming-fishing      Husband   White     Male             0   
2     Protective-serv      Husband   White     Male             0   
3   Machine-op-inspct      Husband   Black     Male          7688   
4                   ?    Own-child   White   Female             0   

   capital_loss  hours_per_week  native_country wage_class  
0             0              40   United-States     <=50K.  
1             0              50   United-States     <=50K.  
2             0              40   United-States      >50K.  
3             0              40   United-States      >50K.  
4             0              30   United-States     <=50K.

In [227]:
train_set[train_set.isnull().any(axis=1)]

Empty DataFrame
Columns: [age, workclass, fnlwgt, education, education_num, marital_status, occupation, relationship, race, sex, capital_gain, capital_loss, hours_per_week, native_country, wage_class]
Index: []

In [228]:
train_set.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
wage_class        object
dtype: object

In [268]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor

In [136]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
# integer encode
label_encoder = LabelEncoder()
train_set['native_country'] = label_encoder.fit_transform(train_set['native_country'])
array = train_set.values
X = array[:,0:14]
Y = array[:,14]
#train_set['native_country']=train_set['native_country'].astype('category')
print(X)
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(train_set['native_country']), 1)
print(integer_encoded)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
df=pd.DataFrame(onehot_encoded)
train_set=pd.concat([train_set,df],axis=1)

#onehotencoder = OneHotEncoder(categorical_features = [14])
#X = onehotencoder.fit_transform(X).toarray()


[[39 ' State-gov' 77516 ..., 0 40 39]
 [50 ' Self-emp-not-inc' 83311 ..., 0 13 39]
 [38 ' Private' 215646 ..., 0 40 39]
 ..., 
 [58 ' Private' 151910 ..., 0 40 39]
 [22 ' Private' 201490 ..., 0 20 39]
 [52 ' Self-emp-inc' 287927 ..., 0 40 39]]
[[39]
 [39]
 [39]
 ..., 
 [39]
 [39]
 [39]]


In [230]:
train_set.head()

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country wage_class  
0          2174             0              40   United-States      <=50K  
1             0             0              13   United-States      <=50K  
2             0             0              40   United-States      <=50K  
3             0             0              40   United-States      <=50K  
4             0             0              40            Cuba      <=50K

In [283]:
# feature extraction
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

model = LogisticRegression()
# integer encode
label_encoder = LabelEncoder()
train_set['native_country'] = label_encoder.fit_transform(train_set['native_country'])
train_set['sex'] = label_encoder.fit_transform(train_set['sex'])
train_set['race'] = label_encoder.fit_transform(train_set['race'])
train_set['relationship'] = label_encoder.fit_transform(train_set['relationship'])
train_set['occupation'] = label_encoder.fit_transform(train_set['occupation'])
train_set['marital_status'] = label_encoder.fit_transform(train_set['marital_status'])
train_set['education'] = label_encoder.fit_transform(train_set['education'])
train_set['workclass'] = label_encoder.fit_transform(train_set['workclass'])
train_set['wage_class'] = label_encoder.fit_transform(train_set['wage_class'])

test_set['native_country'] = label_encoder.fit_transform(test_set['native_country'])
test_set['sex'] = label_encoder.fit_transform(test_set['sex'])
test_set['race'] = label_encoder.fit_transform(test_set['race'])
test_set['relationship'] = label_encoder.fit_transform(test_set['relationship'])
test_set['occupation'] = label_encoder.fit_transform(test_set['occupation'])
test_set['marital_status'] = label_encoder.fit_transform(test_set['marital_status'])
test_set['education'] = label_encoder.fit_transform(test_set['education'])
test_set['workclass'] = label_encoder.fit_transform(test_set['workclass'])
test_set['wage_class'] = label_encoder.fit_transform(test_set['wage_class'])


array = train_set.values

X = array[:,0:14]
Y = array[:,14]
rfe = RFE(model, 4)
fit = rfe.fit(X, Y)
print( fit.n_features_)
print( fit.support_)
print(fit.ranking_)
train_set.head()

4
[False False False False  True  True False  True False  True False False
 False False]
[ 3  5 11  6  1  1  7  1  2  1 10  9  4  8]


age  workclass  fnlwgt  education  education_num  marital_status  \
0   39          7   77516          9             13               4   
1   50          6   83311          9             13               2   
2   38          4  215646         11              9               0   
3   53          4  234721          1              7               2   
4   28          4  338409          9             13               2   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           1             1     4    1          2174             0   
1           4             0     4    1             0             0   
2           6             1     4    1             0             0   
3           6             0     2    1             0             0   
4          10             5     2    0             0             0   

   hours_per_week  native_country  wage_class  
0              40              39           0  
1              13              39           0  
2              40              39           0  
3              40              39           0  
4              40               5           0

In [284]:
onehotencoder = OneHotEncoder(categorical_features = [5])
X = onehotencoder.fit_transform(X).toarray()

In [285]:
X_Train=train_set[['education_num','marital_status','relationship','sex']]
Y_Train=train_set['wage_class']
model.fit(X_Train,Y_Train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [286]:
X_Test=test_set[['education_num','marital_status','relationship','sex']]
Y_Test=test_set['wage_class']

predictedLg=model.predict(X_Test)
print(predictedLg)

[0 0 0 ..., 1 1 1]


In [287]:
from sklearn import metrics
from sklearn.metrics import classification_report

#Derive the Accuracy score
metrics.accuracy_score(Y_Test,predictedLg)

0.80775136662367175

In [288]:
modelTr=DecisionTreeClassifier()
modelTr.fit(X_Train,Y_Train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [289]:
predicted = modelTr.predict(X_Test)
print(predicted)

[0 0 0 ..., 1 0 1]


In [290]:
metrics.accuracy_score(Y_Test,predicted)

0.82255389718076288

In [291]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

In [292]:
gb = GradientBoostingClassifier(n_estimators=20, learning_rate = 0.5, max_features=2, max_depth = 2, random_state = 0)
gb.fit(X_Train, Y_Train)
predictions = gb.predict(X_Test)

print("Confusion Matrix:")
print(confusion_matrix(Y_Test, predictions))
print()
print("Classification Report")
print(classification_report(Y_Test, predictions))

Confusion Matrix:
[[11767   668]
 [ 2213  1633]]

Classification Report
             precision    recall  f1-score   support

          0       0.84      0.95      0.89     12435
          1       0.71      0.42      0.53      3846

avg / total       0.81      0.82      0.81     16281

